version: "2"
services:
  plone:
    image: plone:4
    ports:
    - "8080"
    volumes:
    - ../../:/plone/instance/src/eea.api.layout
    environment:
      ADDONS: "eea.api.layout[test]"
      DEVELOP: "src/eea.api.layout"
